configfile: os.path.join(workflow.basedir, "../defaults/clade-i/config.yaml")

if os.path.exists("config.yaml"):
    configfile: "config.yaml"


include:"../rules/main.smk"

rule _all:
    input: rules.all.input
