# Pathogen NCBI Taxonomy ID
ncbi_taxon_id: '10244'
# The list of NCBI Datasets fields to include from NCBI Datasets output
# These need to be the "mnemonics" of the NCBI Datasets fields, see docs for full list of fields
# https://www.ncbi.nlm.nih.gov/datasets/docs/v2/reference-docs/command-line/dataformat/tsv/dataformat_tsv_virus-genome/#fields
# Note: the "accession" field MUST be provided to match with the sequences
ncbi_datasets_fields:
  - accession
  - sourcedb
  - isolate-lineage
  - geo-region
  - geo-location
  - isolate-collection-date
  - release-date
  - update-date
  - length
  - host-name
  - isolate-lineage-source
  - bioprojects
  - biosample-acc
  - sra-accs
  - submitter-names
  - submitter-affiliation

### TO DELETE ABOVE

# Params for the curate rule
curate:
  # Fields to rename.
  # This is the first step in the pipeline, so any references to field names
  # in the configs below should use the new field names
  field_map:
    accession: accession
    accessionVersion: accession_version
    insdcAccessionBase: genbank_accession
    insdcAccessionFull: genbank_accession_rev
    # sourcedb: database  # Where original submission was made: Pathoplexus vs INSDC
    specimenCollectorSampleId: strain
    geoLocContinent: region
    geoLocCountry: country
    geoLocAdmin1: division
    geoLocAdmin2: location
    geoLocCity: city
    geoLocSite: site
    # geo-region: region # We need to derive region from country (possibly do in PPX preprocessing)
    sampleCollectionDate: date
    earliestReleaseDate: date_released
    releasedDate: date_updated
    length: length
    hostNameScientific: host
    # isolate-lineage-source: isolation_source
    bioprojectAccession: bioproject_accession
    biosampleAccession: biosample_accessions
    insdcRawReadsAccession: sra_accession
    authors: full_authors
    authorAffiliations: institution
    # TODO: There are more fields I should look into porting
  # Standardized strain name regex
  # Currently accepts any characters because we do not have a clear standard for strain names
  strain_regex: '^.+$'
  # Back up strain name field if 'strain' doesn't match regex above
  strain_backup_fields: ['submissionId','accession']
  # List of date fields to standardize
  date_fields: ['date', 'date_released', 'date_updated']
  # Expected date formats present in date fields
  # These date formats should use directives expected by datetime
  # See https://docs.python.org/3.9/library/datetime.html#strftime-and-strptime-format-codes
  expected_date_formats: ['%Y', '%Y-%m', '%Y-%m-%d', '%Y-%m-%dT%H:%M:%SZ']
  # Titlecase rules
  titlecase:
    # Abbreviations not cast to titlecase, keeps uppercase
    abbreviations: ['USA']
    # Articles that should not be cast to titlecase
    articles: [
      'and', 'd', 'de', 'del', 'des', 'di', 'do', 'en', 'l', 'la', 'las', 'le',
      'los', 'nad', 'of', 'op', 'sur', 'the', 'y'
    ]
    # List of string fields to titlecase
    fields: ['region', 'country', 'division', 'location']
  # Authors field name
  authors_field: 'full_authors'
  # Authors default value if authors value is empty
  authors_default_value: '?'
  # Field name for the generated abbreviated authors
  abbr_authors_field: 'authors'
  # Local geolocation rules that are only applicable to mpox data
  local_geolocation_rules: 'geolocation-rules.tsv'
  # User annotations file
  annotations: 'annotations.tsv'
  # ID field used to merge annotations
  annotations_id: 'accession'
  # Field to use as the sequence ID in the FASTA file
  id_field: 'accession'
  # Field to use as the sequence in the FASTA file
  sequence_field: 'sequence'
  # The field in the NDJSON record that contains the actual GenBank accession
  # TODO: Check what the purpose of this is
  genbank_accession: 'accession'
  # Final output columns for the metadata TSV
  metadata_columns: [
    'accession',
    'genbank_accession_rev',
    'strain',
    'date',
    'region',
    'country',
    'division',
    'location',
    'length',
    'host',
    'date_released',
    'date_updated',
    'sra_accession',
    'authors',
    'full_authors',
    'institution',
    'url'
  ]

# Params for Nextclade related rules
nextclade:
  # Field to use as the sequence ID in the Nextclade file
  id_field: 'seqName'
  # The first column should be the original column name of the Nextclade TSV
  # The second column should be the new column name to use in the final metadata TSV
  # Nextclade can have pathogen specific output columns so make sure to check which
  # columns would be useful for your downstream phylogenetic analysis.
  field_map:
    seqName: "seqName"
    clade: "clade"
    outbreak: "outbreak"
    lineage: "lineage"
    coverage: "coverage"
    totalMissing: "missing_data"
    totalSubstitutions: "divergence"
    totalNonACGTNs: "nonACGTN"
    qc.missingData.status: "QC_missing_data"
    qc.mixedSites.status: "QC_mixed_sites"
    qc.privateMutations.status: "QC_rare_mutations"
    qc.frameShifts.status: "QC_frame_shifts"
    qc.stopCodons.status: "QC_stop_codons"
    frameShifts: "frame_shifts"
    isReverseComplement: "is_reverse_complement"
