from snakemake.utils import min_version

min_version(
    "7.7.0"
)  # Snakemake 7.7.0 introduced `retries` directive used in fetch-sequences


# Use default configuration values. Override with Snakemake's --configfile/--config options.
configfile: "defaults/config.yaml"


# This is the default rule that Snakemake will run when there are no specified targets.
rule all:
    input:
        "results/sequences.fasta",
        "results/metadata.tsv",


include: "rules/fetch_from_ncbi.smk"
include: "rules/transform.smk"
include: "rules/nextclade.smk"


if "custom_rules" in config:
    for rule_file in config["custom_rules"]:

        include: rule_file
