# I was hoping to use the Snakemake `default_target` directive to make this the
# default target when including this rule via `custom_rules`, but that is
# currently not possible: https://github.com/snakemake/snakemake/issues/2056
rule update_example_data:
    """This updates the files under example_data/ based on latest available data from data.nextstrain.org.

    The subset of data is generated by an augur filter call which:
    - sets the subsampling size to 50
    - includes the root (defined in config but hardcoded here)
    - ensures all clades and lineages are accounted for using --group-by
    """
    input:
        sequences="results/sequences.fasta",
        metadata="results/metadata.tsv",
    output:
        sequences="example_data/sequences.fasta",
        metadata="example_data/metadata.tsv",
    params:
        strain_id=config["strain_id_field"],
    shell:
        """
        augur filter \
            --metadata {input.metadata} \
            --metadata-id-columns {params.strain_id} \
            --sequences {input.sequences} \
            --include-where PPX_accession=PP_000T4L2 PPX_accession=PP_000T4J6 \
            --group-by clade lineage \
            --subsample-max-sequences 50 \
            --subsample-seed 0 \
            --output-metadata {output.metadata} \
            --output-sequences {output.sequences}
        """
