reference: "config/reference.fasta"
genemap: "config/genemap.gff"
genbank_reference: "config/reference.gb"
include: "config/hmpxv1/include.txt"
clades: "config/clades.tsv"
lat_longs: "config/lat_longs.tsv"
auspice_config: "config/hmpxv1/auspice_config.json"
description: "config/description.md"
tree_mask: "config/tree_mask.tsv"

# Use `accession` as the ID column since `strain` currently contains duplicates¹.
# ¹ https://github.com/nextstrain/mpox/issues/33
strain_id_field: "accession"
display_strain_field: "strain"

build_name: "hmpxv1"
auspice_name: "mpox_clade-IIb"

filter:
  exclude: "config/exclude_accessions.txt"
  min_date: 2017
  min_length: 100000


### Set 1: Non-B.1 sequences: use all
### Set 2: B.1 sequences: small sample across year/country, maybe month
subsample:
  non_b1:
    group_by:
      - lineage
      - year
      - country
    sequences_per_group: 50
    exclude_where:
      - outbreak!=hMPXV-1
      - clade!=IIb
      - lineage=B.1
      - lineage=B.1.1
      - lineage=B.1.2
      - lineage=B.1.3
      - lineage=B.1.4
      - lineage=B.1.5
      - lineage=B.1.6
      - lineage=B.1.7
      - lineage=B.1.8
      - lineage=B.1.9
      - lineage=B.1.10
      - lineage=B.1.11
      - lineage=B.1.12
      - lineage=B.1.13
      - lineage=B.1.14
      - lineage=B.1.15
      - lineage=B.1.16
      - lineage=B.1.17
      - lineage=B.1.18
      - lineage=B.1.19
      - lineage=B.1.20
      - lineage=C.1
  b1:
    group_by:
      - country
      - year
    subsample_max_sequences: 100
    exclude_where:
      - outbreak!=hMPXV-1
      - clade!=IIb

## align
max_indel: 10000
seed_spacing: 1000

## treefix
fix_tree: true
treefix_root: "--root MK783032"

## refine
timetree: true
root: "MK783032 MK783030"
clock_rate: 5.7e-5
clock_std_dev: 2e-5
divergence_units: "mutations"

## recency
recency: true

mask:
  from_beginning: 800
  from_end: 6422
  maskfile: "config/mask.bed"
