auspice_config: "config/mpxv/auspice_config.json"
include: "config/mpxv/include.txt"
reference: "config/reference.fasta"
genemap: "config/genemap.gff"
genbank_reference: "config/reference.gb"
lat_longs: "config/lat_longs.tsv"
description: "config/description.md"
clades: "config/clades.tsv"
tree_mask: "config/tree_mask.tsv"

# Use `accession` as the ID column since `strain` currently contains duplicates¹.
# ¹ https://github.com/nextstrain/monkeypox/issues/33
strain_id_field: "accession"
display_strain_field: "strain"

build_name: "mpxv"
auspice_name: "mpox_all-clades"

filter:
  exclude: "config/exclude_accessions.txt"
  min_date: 1950
  min_length: 100000

### Set 1: Non-B.1 sequences: use all
### Set 2: B.1 sequences: small sample across year/country, maybe month
subsample:
  non_b1:
    group_by: "--group-by clade year country"
    sequences_per_group: "--sequences-per-group 50"
    exclude_lineages:
      - B.1
      - B.1.1
      - B.1.2
      - B.1.3
      - B.1.4
      - B.1.5
      - B.1.6
      - B.1.7
      - B.1.8
      - B.1.9
      - B.1.10
      - B.1.11
      - B.1.12
      - B.1.13
      - B.1.14
      - B.1.15
      - B.1.16
      - B.1.17
      - B.1.18
      - B.1.19
      - B.1.20
      - C.1
  b1:
    group_by: "--group-by country year"
    sequences_per_group: "--subsample-max-sequences 100"

## align
max_indel: 10000
seed_spacing: 1000

## treefix
fix_tree: true

## refine
timetree: false
root: "min_dev"
clock_rate: 3e-6
clock_std_dev: 6e-6

## recency
recency: true

mask:
  from_beginning: 1350
  from_end: 6422
  maskfile: "config/mask_overview.bed"
