# Mostly reuse the clade-i config
reference: "defaults/clade-i/reference.fasta"
genome_annotation: "defaults/clade-i/genome_annotation.gff3"
genbank_reference: "defaults/clade-i/reference.gb"
include: "defaults/clade-ib/include.txt"
clades: "defaults/clades.tsv"
lat_longs: "defaults/lat_longs.tsv"
auspice_config: "defaults/clade-ib/auspice_config.json"
description: "defaults/description.md"
tree_mask: "defaults/clade-i/tree_mask.tsv"

# Use `accession` as the ID column since `strain` currently contains duplicates¹.
# ¹ https://github.com/nextstrain/mpox/issues/33
strain_id_field: "accession"
display_strain_field: "strain"

private_metadata: "data/gisaid_massaged.tsv"
private_sequences: "data/gisaid_massaged.fasta"

build_name: "clade-ib"
auspice_name: "mpox_clade-Ib"

filter:
  min_length: 170000


### Filter to only Clade I sequences
subsample:
  everything:
    group_by: ""
    sequences_per_group: ""
    query: "'clade in [\"Ib\"]'"

## align
max_indel: 10000
seed_spacing: 1000

## treefix
fix_tree: true
treefix_root: "--root EPI_ISL_19093833" # without a root we'll midpoint root which should work great for clade I

## refine
timetree: true
root: "best"
keep_polytomies: false

divergence_units: "mutations"


traits:
  columns: region country
  sampling_bias_correction: 3

## recency
recency: true

mask:
  from_beginning: 800
  from_end: 6422
  maskfile: "defaults/clade-i/mask.bed"

colors:
  ignore_categories: "division location"
