# Custom config file for INRB Clade-I builds.
# This should be used as an additional config on top of the clade-i config, i.e.
# --configfile defaults/clade-i/config.yaml build-configs/inrb/config.yaml

# Custom INRB footer contents & auspice config
description: "build-configs/inrb/description.md"
auspice_config: "build-configs/inrb/auspice_config.json"

# INRB builds inject private data, which is itself created by calling `curate_private_data.py`
private_sequences: "data/sequences-private.fasta"
private_metadata: "data/metadata-private.tsv"

traits:
  columns:
    - region
    - country
    - division
    - location
  sampling_bias_correction: 3

# Private INRB data doesn't have clade annotations so allow empty clade fields
# (i.e. we're assuming all INRB data is clade I)
subsample:
  everything:
    query: clade in ["I", "Ia", "Ib", ""]
