reference: "config/reference.fasta"
genemap: "config/genemap.gff"
genbank_reference: "config/reference.gb"
colors: "config/colors_hmpxv1.tsv"
clades: "config/clades.tsv"
lat_longs: "config/lat_longs.tsv"
auspice_config: "config/auspice_config_hmpxv1.json"
description: "config/description.md"
tree_mask: "config/tree_mask.tsv"

# Use `accession` as the ID column since `strain` currently contains duplicates¹.
# ¹ https://github.com/nextstrain/monkeypox/issues/33
strain_id_field: "accession"
display_strain_field: "strain"

build_name: "hmpxv1"
auspice_name: "mpox_clade-IIb"

filter:
  exclude: "config/exclude_accessions_mpxv.txt"
  min_date: 2017
  min_length: 100000


### Set 1: Non-B.1 sequences: use all
### Set 2: B.1 sequences: small sample across year/country, maybe month
subsample:
  non_b1:
    group_by: "--group-by lineage year country"
    sequences_per_group: "--sequences-per-group 50"
    other_filters: "outbreak!=hMPXV-1 clade!=IIb"
    exclude_lineages:
      - B.1
      - B.1.1
      - B.1.2
      - B.1.3
      - B.1.4
      - B.1.5
      - B.1.6
      - B.1.7
      - B.1.8
      - B.1.9
      - B.1.10
      - B.1.11
      - B.1.12
      - B.1.13
      - B.1.14
      - B.1.15
      - B.1.16
      - B.1.17
      - B.1.18
      - B.1.19
      - B.1.20
      - C.1
  b1:
    group_by: "--group-by country year"
    sequences_per_group: "--subsample-max-sequences 100"
    other_filters: "--exclude-where outbreak!=hMPXV-1 clade!=IIb"

## align
max_indel: 10000
seed_spacing: 1000

## treefix
fix_tree: true
treefix_root: "--root MK783032"

## refine
timetree: true
root: "MK783032 MK783030"
clock_rate: 5.7e-5
clock_std_dev: 2e-5

## recency
recency: true

mask:
  from_beginning: 800
  from_end: 6422
  maskfile: "config/mask.bed"
