name: Rebuild mpxv

on:
  repository_dispatch:
    types:
      - rebuild
      - rebuild_mpxv

  workflow_dispatch:
    inputs:
      trial_name:
        description: "If set, result will be at nextstrain.org/staging/trial/trial_name/monkeypox/mpxv"
        required: false
      image:
        description: 'Specific container image to use for build (will override the default of "nextstrain build")'
        required: false

env:
  TRIAL_NAME: ${{ github.event.inputs.trial_name }}
  NEXTSTRAIN_DOCKER_IMAGE: ${{ github.event.inputs.image }}

jobs:
  rebuild_mpxv:
    permissions:
      id-token: write
    uses: nextstrain/.github/.github/workflows/pathogen-repo-build.yaml@master
    secrets: inherit
    with:
      runtime: aws-batch
      env: |
        NEXTSTRAIN_DOCKER_IMAGE: ${{ inputs.image }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        SLACK_CHANNELS: monkeypox-updates
        BUILD_DIR: phylogenetic
      run: |
        nextstrain build \
          --detach \
          --no-download \
          --cpus 8 \
          --memory 32gib \
          --env AWS_DEFAULT_REGION \
          --env AWS_ACCESS_KEY_ID \
          --env AWS_SECRET_ACCESS_KEY \
          --env GITHUB_RUN_ID \
          --env SLACK_TOKEN \
          --env SLACK_CHANNELS \
          . \
            notify_on_deploy \
              --configfiles $BUILD_DIR/config/mpxv/config.yaml $BUILD_DIR/config/nextstrain_automation.yaml \
              --config auspice_prefix=$TRIAL_NAME --directory $BUILD_DIR --snakefile $BUILD_DIR/Snakefile
